name: Docker image build and publish
on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check variables
        run: |
          echo "AWS_ACCOUNT_ID : ${{ vars.AWS_ACCOUNT_ID }}:"
          echo "AWS_REGION : ${{ vars.AWS_REGION }}"
          echo "AWS_ACCESS_KEY_ID : ${{ vars.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY : ${{ vars.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_SESSION_TOKEN : ${{ vars.AWS_SESSION_TOKEN }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-rmodi
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ vars.AWS_SESSION_TOKEN }}

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: coworking
